import React, {useState, useEffect} from 'react';
import {Section} from '@astryxdesign/core/Section';
import {VStack} from '@astryxdesign/core/VStack';
import {HStack} from '@astryxdesign/core/HStack';
import {Text} from '@astryxdesign/core/Text';
import {Heading} from '@astryxdesign/core/Heading';
import {Button} from '@astryxdesign/core/Button';
import {Card} from '@astryxdesign/core/Card';
import {Divider} from '@astryxdesign/core/Divider';
import {StatusDot} from '@astryxdesign/core/StatusDot';

const RAW = 'https://raw.githubusercontent.com/bakathefish/Flood/master/';

const A_T = {
  en: {
    no: '03',
    title: 'Alerts in your language',
    intro: 'The last mile: every satellite pass turns into a plain-language alert, issued in Punjabi, Hindi, and English.',
    pickHint: 'Pick a district to read its current alert.',
    pick: 'Pick a district',
    monitoring: 'MONITORING',
    warning: 'FLOOD ALERT',
    note: 'Auto-generated by the monitor from each district’s live numbers and committed to the public repo on every run; the Punjabi and Hindi wording was reviewed by a native reader. A warning is raised automatically the moment a district crosses the alert floor.',
    emptyUnknown: 'No standing water was found in this pass, but how much of Punjab it covered could not be determined. Treat this as unknown coverage, not as an all-clear.',
    empty: (cov) => `No standing water in the area this window's satellite pass covered (about ${cov}% of Punjab; each Sentinel-1 pass images a strip, not the whole state at once). Coverage fills in over the 12-day revisit, and alerts appear the moment water rises.`,
    loading: 'Loading the latest satellite window…',
    err: 'Live monitor unreachable right now. This is a connection problem, not an all-clear; please retry shortly.',
    mon: (d, km2, floor) => `${d}: ${km2} km² of standing water in the latest satellite window, below the ${floor} km² alert floor. No action needed now. Sailaab keeps watching and will raise an alert automatically if water rises. Helpline 1070.`,
    warn: (d, km2, floor) => `${d}: about ${km2} km² is under water (satellite-detected), above the ${floor} km² alert floor and rising. Move people, livestock, and valuables to higher ground and follow district instructions. Helpline 1070.`,
  },
  hi: {
    no: '03',
    title: 'आपकी भाषा में चेतावनियाँ',
    intro: 'आख़िरी कड़ी: हर सैटेलाइट पास एक सरल-भाषा चेतावनी बन जाता है, पंजाबी, हिन्दी व अंग्रेज़ी में जारी।',
    pickHint: 'किसी ज़िले की मौजूदा चेतावनी पढ़ने के लिए उसे चुनें।',
    pick: 'ज़िला चुनें',
    monitoring: 'निगरानी',
    warning: 'बाढ़ चेतावनी',
    note: 'हर ज़िले के लाइव आँकड़ों से मॉनिटर द्वारा स्वतः तैयार और हर रन पर सार्वजनिक रिपॉज़िटरी में कमिट; पंजाबी व हिन्दी शब्दावली एक मूल पाठक द्वारा जाँची गई। जैसे ही कोई ज़िला अलर्ट सीमा पार करता है, चेतावनी अपने आप जारी होती है।',
    emptyUnknown: 'इस पास में कोई स्थिर जल नहीं मिला, पर इसने पंजाब का कितना हिस्सा कवर किया यह तय नहीं हो सका। इसे अज्ञात कवरेज समझें, सुरक्षा की सूचना नहीं।',
    empty: (cov) => `इस विंडो के सैटेलाइट पास ने जो क्षेत्र कवर किया (पंजाब का लगभग ${cov}%; हर Sentinel-1 पास पूरा राज्य नहीं, एक पट्टी लेता है) उसमें कोई स्थिर जल नहीं। 12-दिन के पुनरावर्तन में कवरेज भरती जाती है, और पानी बढ़ते ही चेतावनियाँ दिखेंगी।`,
    loading: 'नवीनतम सैटेलाइट विंडो लोड हो रही है…',
    err: 'लाइव मॉनिटर अभी अनुपलब्ध है। यह कनेक्शन समस्या है, ऑल-क्लियर नहीं; कृपया थोड़ी देर बाद पुनः प्रयास करें।',
    mon: (d, km2, floor) => `${d}: नवीनतम सैटेलाइट विंडो में ${km2} km² स्थिर जल, ${floor} km² अलर्ट सीमा से नीचे। अभी कार्रवाई की ज़रूरत नहीं। सैलाब नज़र रखे हुए है और पानी बढ़ने पर अपने आप चेतावनी देगा। हेल्पलाइन 1070।`,
    warn: (d, km2, floor) => `${d}: लगभग ${km2} km² क्षेत्र जलमग्न है (सैटेलाइट द्वारा पहचाना), ${floor} km² सीमा से ऊपर और बढ़ रहा। लोगों, पशुओं व क़ीमती सामान को ऊँचे स्थान पर ले जाएँ और ज़िला निर्देशों का पालन करें। हेल्पलाइन 1070।`,
  },
  pa: {
    no: '03',
    title: 'ਤੁਹਾਡੀ ਭਾਸ਼ਾ ਵਿੱਚ ਚੇਤਾਵਨੀਆਂ',
    intro: 'ਆਖ਼ਰੀ ਕੜੀ: ਹਰ ਸੈਟੇਲਾਈਟ ਪਾਸ ਇੱਕ ਸਰਲ-ਭਾਸ਼ਾ ਚੇਤਾਵਨੀ ਬਣ ਜਾਂਦਾ ਹੈ, ਪੰਜਾਬੀ, ਹਿੰਦੀ ਤੇ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਜਾਰੀ।',
    pickHint: 'ਕਿਸੇ ਜ਼ਿਲ੍ਹੇ ਦੀ ਮੌਜੂਦਾ ਚੇਤਾਵਨੀ ਪੜ੍ਹਨ ਲਈ ਉਸ ਨੂੰ ਚੁਣੋ।',
    pick: 'ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ',
    monitoring: 'ਨਿਗਰਾਨੀ',
    warning: 'ਹੜ੍ਹ ਚੇਤਾਵਨੀ',
    note: 'ਹਰ ਜ਼ਿਲ੍ਹੇ ਦੇ ਲਾਈਵ ਅੰਕੜਿਆਂ ਤੋਂ ਮਾਨੀਟਰ ਵੱਲੋਂ ਸਵੈ-ਤਿਆਰ ਅਤੇ ਹਰ ਰਨ ਉੱਤੇ ਜਨਤਕ ਰਿਪੋਜ਼ਟਰੀ ਵਿੱਚ ਕਮਿਟ; ਪੰਜਾਬੀ ਤੇ ਹਿੰਦੀ ਸ਼ਬਦਾਵਲੀ ਇੱਕ ਮੂਲ ਪਾਠਕ ਵੱਲੋਂ ਜਾਂਚੀ ਗਈ। ਜਿਵੇਂ ਹੀ ਕੋਈ ਜ਼ਿਲ੍ਹਾ ਅਲਰਟ ਹੱਦ ਪਾਰ ਕਰਦਾ ਹੈ, ਚੇਤਾਵਨੀ ਆਪਣੇ ਆਪ ਜਾਰੀ ਹੁੰਦੀ ਹੈ।',
    emptyUnknown: 'ਇਸ ਪਾਸ ਵਿੱਚ ਕੋਈ ਖੜ੍ਹਾ ਪਾਣੀ ਨਹੀਂ ਮਿਲਿਆ, ਪਰ ਇਸ ਨੇ ਪੰਜਾਬ ਦਾ ਕਿੰਨਾ ਹਿੱਸਾ ਕਵਰ ਕੀਤਾ ਇਹ ਤੈਅ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਇਸ ਨੂੰ ਅਣਜਾਣ ਕਵਰੇਜ ਸਮਝੋ, ਸੁਰੱਖਿਆ ਦੀ ਸੂਚਨਾ ਨਹੀਂ।',
    empty: (cov) => `ਇਸ ਵਿੰਡੋ ਦੇ ਸੈਟੇਲਾਈਟ ਪਾਸ ਨੇ ਜੋ ਖੇਤਰ ਕਵਰ ਕੀਤਾ (ਪੰਜਾਬ ਦਾ ਲਗਭਗ ${cov}%; ਹਰ Sentinel-1 ਪਾਸ ਪੂਰਾ ਸੂਬਾ ਨਹੀਂ, ਇੱਕ ਪੱਟੀ ਲੈਂਦਾ ਹੈ) ਉਸ ਵਿੱਚ ਕੋਈ ਖੜ੍ਹਾ ਪਾਣੀ ਨਹੀਂ। 12-ਦਿਨ ਦੇ ਪੁਨਰ-ਦੌਰੇ ਵਿੱਚ ਕਵਰੇਜ ਭਰਦੀ ਜਾਂਦੀ ਹੈ, ਅਤੇ ਪਾਣੀ ਵਧਦਿਆਂ ਹੀ ਚੇਤਾਵਨੀਆਂ ਦਿਖਣਗੀਆਂ।`,
    loading: 'ਨਵੀਨਤਮ ਸੈਟੇਲਾਈਟ ਵਿੰਡੋ ਲੋਡ ਹੋ ਰਹੀ ਹੈ…',
    err: 'ਲਾਈਵ ਮਾਨੀਟਰ ਹੁਣੇ ਉਪਲਬਧ ਨਹੀਂ। ਇਹ ਕਨੈਕਸ਼ਨ ਸਮੱਸਿਆ ਹੈ, ਆਲ-ਕਲੀਅਰ ਨਹੀਂ; ਕਿਰਪਾ ਕਰਕੇ ਥੋੜ੍ਹੀ ਦੇਰ ਬਾਅਦ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    mon: (d, km2, floor) => `${d}: ਨਵੀਨਤਮ ਸੈਟੇਲਾਈਟ ਵਿੰਡੋ ਵਿੱਚ ${km2} km² ਖੜ੍ਹਾ ਪਾਣੀ, ${floor} km² ਅਲਰਟ ਹੱਦ ਤੋਂ ਹੇਠਾਂ। ਹੁਣ ਕਾਰਵਾਈ ਦੀ ਲੋੜ ਨਹੀਂ। ਸੈਲਾਬ ਨਜ਼ਰ ਰੱਖ ਰਿਹਾ ਹੈ ਅਤੇ ਪਾਣੀ ਵਧਣ ਉੱਤੇ ਆਪਣੇ ਆਪ ਚੇਤਾਵਨੀ ਦੇਵੇਗਾ। ਹੈਲਪਲਾਈਨ 1070।`,
    warn: (d, km2, floor) => `${d}: ਲਗਭਗ ${km2} km² ਖੇਤਰ ਪਾਣੀ ਹੇਠ ਹੈ (ਸੈਟੇਲਾਈਟ ਦੁਆਰਾ ਪਛਾਣਿਆ), ${floor} km² ਹੱਦ ਤੋਂ ਉੱਪਰ ਤੇ ਵਧ ਰਿਹਾ। ਲੋਕਾਂ, ਪਸ਼ੂਆਂ ਤੇ ਕੀਮਤੀ ਸਮਾਨ ਨੂੰ ਉੱਚੀ ਥਾਂ ਲੈ ਜਾਓ ਅਤੇ ਜ਼ਿਲ੍ਹਾ ਹਦਾਇਤਾਂ ਦੀ ਪਾਲਣਾ ਕਰੋ। ਹੈਲਪਲਾਈਨ 1070।`,
  },
};

export default function AlertSection({lang}) {
  const t = A_T[lang] || A_T.en;
  const [data, setData] = useState(null);
  const [sel, setSel] = useState(null);
  const [status, setStatus] = useState('loading');

  useEffect(() => {
    let on = true;
    fetch(RAW + 'monitor/latest.json')
      .then((r) => r.json())
      .then((j) => {
        if (!on) return;
        setData(j);
        setStatus('ok');
        const withWater = (j.districts || []).filter((d) => +d.flooded_km2 > 0).sort((a, b) => b.flooded_km2 - a.flooded_km2);
        if (withWater[0]) setSel(withWater[0].district);
      })
      .catch(() => { if (on) setStatus('error'); });
    return () => {
      on = false;
    };
  }, []);

  const floor = data ? data.alert_floor_km2 || 25 : 25;
  // null, not 0: an unknown coverage fraction shown as 0% is wrong in the
  // reassuring direction, because a reader reads it as "nothing was flooded".
  const covRaw = data && typeof data.coverage_fraction === 'number'
    && Number.isFinite(data.coverage_fraction) ? data.coverage_fraction : null;
  const cov = covRaw === null ? null : Math.round(covRaw * 100);
  const districts = data ? (data.districts || []).filter((d) => +d.flooded_km2 > 0).sort((a, b) => b.flooded_km2 - a.flooded_km2).slice(0, 8) : [];
  const cur = sel && data ? (data.districts || []).find((d) => d.district === sel) : null;
  const km2 = cur ? (+cur.flooded_km2).toFixed(1) : null;
  const warn = cur ? +cur.flooded_km2 >= floor : false;
  const body = cur ? (warn ? t.warn(sel, km2, floor) : t.mon(sel, km2, floor)) : null;

  return (
    <Section variant="transparent" padding={0} dividers={['bottom']}>
      <HStack justify="center" width="100%">
        <VStack width="100%" maxWidth={1120} paddingInline={4} paddingBlock={8} gap={6} hAlign="start" id="alerts">
          <VStack width="100%" gap={3}>
            <Divider />
            <VStack paddingBlock={1}>
              <Heading level={2}>{t.title}</Heading>
            </VStack>
          </VStack>
          <VStack maxWidth={660}>
            <Text type="large" color="secondary">
              {t.intro}{districts.length > 0 ? ` ${t.pickHint}` : ''}
            </Text>
          </VStack>

          {districts.length > 0 ? (
            <>
              <VStack gap={3}>
                <Text type="label" color="secondary">{t.pick}</Text>
                <HStack gap={2} wrap="wrap">
                  {districts.map((d) => (
                    <Button key={d.district} variant={sel === d.district ? 'primary' : 'secondary'} onClick={() => setSel(d.district)}>
                      {d.district}
                    </Button>
                  ))}
                </HStack>
              </VStack>
              {/* The issued bulletin, set as a plate: the reader is looking
                  at the artefact the pipeline actually emits, so it gets a
                  frame and the sending face rather than page furniture. */}
              <VStack width="100%" maxWidth={820}>
                <Card padding={5}>
                  <VStack gap={4}>
                    <HStack gap={2} vAlign="center" wrap="wrap">
                      <StatusDot variant={warn ? 'error' : 'accent'} label={warn ? 'alert' : 'monitoring'} isPulsing={warn} />
                      <Text type="label" color={warn ? 'primary' : 'secondary'}>{warn ? t.warning : t.monitoring} · {sel}</Text>
                    </HStack>
                    <Text type="large">{body}</Text>
                  </VStack>
                </Card>
              </VStack>
            </>
          ) : status === 'error' ? (
            <Card padding={4}><Text color="secondary">{t.err}</Text></Card>
          ) : status === 'loading' ? (
            <Card padding={4}><Text color="secondary">{t.loading}</Text></Card>
          ) : (
            <Card padding={4}><Text color="secondary">
              {cov === null ? t.emptyUnknown : t.empty(cov)}
            </Text></Card>
          )}

          <Text type="supporting" color="secondary">{t.note}</Text>
        </VStack>
      </HStack>
    </Section>
  );
}
